### ISSUE TITLE
hey can you explain the working of your app ! so that i get to know how its working

### ISSUE THREAD

**Issue by vranacse** [pangguoming/Android-Youtube-LiveStream#1]

**Comment by pangguoming** [comment]
video works good, audio do not work

**Comment by MuthuEphron** [comment]
@pangguoming  is there chance for  modifying the jni code for compiled  in youtube watchme project.

**Comment by Muthukumar39** [comment]
@pangguoming is there chance for modifying the jni code for compiled in youtube watchme project.
